baseURL = "https://www.awildtylerappeared.com/"
languageCode = "en-us"
title = "awildtylerappeared"
theme = "mediumish"
summaryLength = 25
copyright = "Tyler Lucas - All rights reserved"
disqusShortname = "awildtylerappeared"

[params]
  logo = "/images/t-logo.png"
  description =""

[params.author]
  name = "Tyler Lucas"
  thumbnail = "/images/ty-profile.jpg"
  description = "Creator of this blog."

[params.index]
  picture = "/images/this-is-ty.png"
  title = ""
  subtitle = ""
  mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!'''
  alertbar = false

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "blog"
    url = "/posts"
